version: '3'

services:

  eurekaserver:
    build: ./eureka-server
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - appnetwork

  gateway:
    build: ./zuulservice
    image: gateway:latest
    depends_on:
      - eurekaserver
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME =APIGateway
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
    networks:
      - appnetwork

  mysql-cars:
    image: mysql:5.6
    container_name: mysql-cars

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=carsmicroservice
    networks:
      - appnetwork

  mysql-userActivities:
    image: mysql:5.6
    container_name: mysql-userActivities

      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=useractivity
    networks:
      - appnetwork

  mysql-users:
    image: mysql:5.6
    container_name: mysql-users

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=usermicroservice
    networks:
      - appnetwork

  userActivitiesModule:
    build: ./userActivities
    image: userActivitiesModule:latest
    depends_on:
      - mysql-userActivities
      - eurekaserver
      - rabbitmq
      - gateway

      ports:
        - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://localhost:3306/useractivity?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=useractivity
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq


      networks:
        - appnetwork

  carsmodule:
    build: ./cars
    image: carsmodule:latest
    depends_on:
      - mysql-cars
      - eurekaserver
      - rabbitmq
      - gateway

    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://localhost:3306/carsmicroservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=car
      - SPRING_PROFILES_ACTIVE=enableEureka
      - MANAGEMENT.SECURITY.ENABLED=false
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq


    networks:
      - appnetwork

  usersmodule:
    build: ./users
    image: usersmodule:latest
    depends_on:
      - mysql-users
      - eurekaserver
      - rabbitmq
      - gateway

    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-users:3306/usermicroservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=userservice
      - SPRING_PROFILES_ACTIVE=enableEureka
      - MANAGEMENT.SECURITY.ENABLED=false
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq


    networks:
      - appnetwork


  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnetwork


networks:
  appnetwork:
    driver: bridge
