version: '3'

services:

   carsmodel:
    build: ./cars
    image: cars:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL= jjdbc:mysql://localhost:3306/carsmicroservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=cars
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge