FROM openjdk:8-jre-alpine

COPY ./target/userActivities-0.0.1-SNAPSHOT.jar /usr/src/userActivities/
WORKDIR /usr/src/userActivities
EXPOSE 8083
CMD ["java", "-jar", "userActivities-0.0.1-SNAPSHOT.jar"]